# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: nametag

builds:
  - binary: nametag
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - name: nametag
    commit_author:
      name: Nametag Devops
      email: devops@nametag.co
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    caveats: "See https://getnametag.com/docs/cli"
    homepage: "https://getnametag.com"
    description: "Command-line tool for Nametag"
    license: "Apache-2.0"
    test: |
      system "#{bin}/nametag", "--version"
    install: |
      bin.install "{{ .Binary }}" => "{{ .ProjectName }}"
    repository:
      owner: nametaginc
      name: homebrew-tap
      branch: main

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
